name: Compilador Reto PS5
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # Obliga a GitHub a usar el entorno nuevo y esquiva el error de Node.js 20
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Checkout del Repositorio
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Configurar Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar Herramientas de Linux (Arregla Error 100)
        run: |
          sudo apt-get update || true
          sudo apt-get install -y git zip unzip autoconf libtool pkg-config zlib1g-dev \
          libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev \
          build-essential libltdl-dev libgmp-dev libmpfr-dev libmpc-dev

      - name: Instalar Buildozer
        run: |
          pip install --upgrade pip
          pip install "buildozer>=1.5.0" cython virtualenv

      - name: Compilar APK con Buildozer
        run: |
          # python3 -m asegura que encuentre el comando y no salga "command not found"
          yes | python3 -m buildozer android debug

      - name: Subir APK Resultante
        uses: actions/upload-artifact@v4
        with:
          name: App_Reto_PS5
          path: bin/*.apk
