name: Compilador Reto PS5
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Instalar Herramientas
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
          pip3 install --user --upgrade buildozer cython virtualenv

      - name: Cocinando el APK (Buildozer)
        run: |
          export PATH=$PATH:~/.local/bin
          buildozer android debug

      - name: Subir APK Resultante
        uses: actions/upload-artifact@v4
        with:
          name: Mi_App_PS5
          path: bin/*.apk
          
